<?php echo $this->sectionNav([
    'extractors' => $this->translate('Extractors'),
    'metadata-crosswalk' => $this->translate('Metadata crosswalk'),
]); ?>
<div id="extractors" class="section active">
    <table class="tablesaw tablesaw-stack">
        <thead>
            <tr>
                <th><?php echo $this->translate('Extractor'); ?></th>
                <th><?php echo $this->translate('Available'); ?></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($extractors->getRegisteredNames() as $extractorName): ?>
            <?php
            $extractor = $extractors->get($extractorName);
            $isAvailable = $extractor->isAvailable()
                ? sprintf('<span style="color: green;">%s</span>', $this->translate('Yes'))
                : sprintf('<span style="color: red;">%s</span>', $this->translate('No'));
            ?>
            <tr>
                <td><?php echo $extractorName; ?></td>
                <td><?php echo $isAvailable; ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
<div id="metadata-crosswalk" class="section">
    <?php if ($crosswalk): ?>
    <table class="tablesaw tablesaw-stack">
        <thead>
            <tr>
                <th><?php echo $this->translate('Extractor'); ?></th>
                <th><?php echo $this->translate('Pointer'); ?></th>
                <th><?php echo $this->translate('Term'); ?></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($crosswalk as $extractorName => $mapData): ?>
            <?php foreach ($mapData as $pointer => $term): ?>
            <tr>
                <td><?php echo $extractorName; ?></td>
                <td><code><?php echo $pointer; ?></code></td>
                <td><?php echo $term; ?></td>
            </tr>
            <?php endforeach; ?>
        <?php endforeach; ?>
        </tbody>
    </table>
    <?php else: ?>
    <p><?php echo $this->translate('No crosswalk defined.'); ?></p>
    <?php endif; ?>
</div>
