<div id="extract-metadata" class="section">
    <?php foreach ($metadataEntities as $metadataEntity): ?>
    <div class="extractor">
        <h2><?php echo $this->extractMetadata()->getExtractor($metadataEntity->getExtractor())->getLabel(); ?></h2>
        <p><?php echo sprintf(
            $this->translate('Last extracted %s.'),
            $this->i18n()->dateFormat($metadataEntity->getExtracted(), 'long', 'long')
        ); ?></p>
        <?php echo $this->hyperlink('', '#', ['class' => 'expand', 'title' => $this->translate('Expand')]); ?>
        <div class="extracted-metadata collapsible">
            <pre><?php echo json_encode($metadataEntity->getMetadata(), JSON_PRETTY_PRINT); ?></pre>
        </div>
    </div>
    <?php endforeach; ?>
</div>
