<div id="extract-metadata" class="section">
    <?php if ($element): ?>
    <?php echo $this->formRow($element); ?>
    <?php endif; ?>
    <?php foreach ($metadataEntities as $metadataEntity): ?>
    <h2><?php echo $this->extractMetadata()->getExtractor($metadataEntity->getExtractor())->getLabel(); ?></h2>
    <p><?php echo sprintf(
        $this->translate('Last extracted %s.'),
        $this->i18n()->dateFormat($metadataEntity->getExtracted(), 'long', 'long')
    ); ?></p>
    <div>
        <pre><?php echo json_encode($metadataEntity->getMetadata(), JSON_PRETTY_PRINT); ?></pre>
    </div>
    <?php endforeach; ?>
</div>
